Calculator c = new Calculator();
// c.add(10,5);
// // c.printNewMessage('This is new age calc');
    
// // string msg = 'Print this now';
// // c.printNewMessage(msg);

// // string ms999 = 'Nowww how abut this';
// // c.printNewMessage(ms999);
// // string result = c.printAndReturnMessage('Prin this ASAP');
// // system.debug(result);
// integer x = c.add(10,15);
// system.debug('sum =' + x);
// system.debug('sum of 10 and 15 is =>' + x );